import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowLeft, LockKeyhole } from 'lucide-react'

export const Route = createFileRoute('/login')({
  head: () => ({ meta: [{ title: 'Acesso · NOI Artesanal' }, { name: 'description', content: 'Acesso ao sistema NOI Artesanal.' }] }),
  component: Login,
})

function Login() {
  return <main className="grid min-h-dvh lg:grid-cols-2"><section className="hidden bg-[#121212] p-12 text-[#fefefe] lg:flex lg:flex-col lg:justify-between"><div><p className="font-serif text-4xl">NOI</p><p className="font-mono text-xs uppercase tracking-[0.35em] text-[#FFF45C]">artesanal</p></div><div><p className="max-w-md font-serif text-5xl leading-[1.05]">O cuidado de cada pedido, do balcão à cozinha.</p><p className="mt-6 max-w-sm text-sm leading-6 text-[#bdbdbd]">Sistema de operação da pizzaria NOI Artesanal.</p></div><p className="font-mono text-xs text-[#7a7a7a]">PROPRIETÁRIO · REINALDO</p></section><section className="flex items-center justify-center bg-background p-6"><div className="w-full max-w-sm"><Link to="/" className="mb-16 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Voltar ao painel</Link><div className="mb-8"><div className="mb-5 flex size-12 items-center justify-center rounded-xl bg-[#FFF45C] text-[#121212]"><LockKeyhole className="size-5" /></div><h1 className="font-serif text-4xl font-semibold">Entrar no sistema</h1><p className="mt-2 text-sm text-muted-foreground">Acesso restrito à equipe NOI Artesanal.</p></div><form className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium">Usuário</span><input className="h-12 w-full rounded-lg border border-input bg-card px-4 outline-none transition focus:border-[#121212] focus:ring-2 focus:ring-[#FFF45C]" placeholder="Digite seu usuário" /></label><label className="block"><span className="mb-2 block text-sm font-medium">Senha</span><input type="password" className="h-12 w-full rounded-lg border border-input bg-card px-4 outline-none transition focus:border-[#121212] focus:ring-2 focus:ring-[#FFF45C]" placeholder="Digite sua senha" /></label><button type="submit" className="h-12 w-full rounded-lg bg-[#121212] font-bold text-[#fefefe] transition hover:scale-[1.01] hover:bg-[#2a2a2a] focus:outline-none focus:ring-2 focus:ring-[#FFF45C]">Entrar</button></form><p className="mt-6 text-center text-xs text-muted-foreground">Problemas para acessar? Procure o proprietário.</p></div></section></main>
}
